src/backend/API/urls.py
from django.urls import path
from . import views
from .views import CheckTransactionStatus

app_name = 'API'

urlpatterns = [
    path('score', views.game_update, name='game_update'),
    path('scorehistory', views.GameHistoryView.as_view(), name='score_history_api'),
    path('check_transaction_status/<int:game_id>/', views.CheckTransactionStatus.as_view(), name='check_transaction_status'),
]

src/backend/authentication/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views
from django.urls import path
from .views import protected_view
app_name = 'authentication'

urlpatterns = [
    path('', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('protected/', protected_view, name='protected'),
]

src/backend/dashboard/urls.py
from django.urls import path
from . import views


app_name = 'dashboard'

urlpatterns = [
    path('', views.leaderboard, name='leaderboard'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # path('gameHistory/', views.game_history_view, name='gameHistory'),
]

src/backend/djangoProject/urls.py
from django.urls import path, include, re_path
from two_factor.urls import urlpatterns as tf_urls
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

import matchMaking
from game.consumers import GameConsumer
from matchMaking.consumers import MatchMakingConsumer
from tournaments.consumers import TournamentConsumer
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

"""
URL configuration for djangoProject project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.urls import path, include

app_name = 'djangoProject'

urlpatterns = [
    path('', views.home, name="home"),
    path('our_team', views.our_team, name="our_team"),
    path('', include(tf_urls)),  # Admin route
    path('admin/', admin.site.urls),  # Admin route
    path('game/', include('game.urls')),
    path('auth/', include('authentication.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('user/', include('user.urls')),
    path('friends/', include('friends.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('API.urls')),
    path('leaderboard/', include('dashboard.urls')),
    path('matchMaking', include('matchMaking.urls')),
    path('tournament/', include('tournaments.urls')),
]

websocket_urlpatterns = [
    re_path(r'ws/game/(?P<room_id>\d+)/$', GameConsumer.as_asgi()), # Map WebSocket path to consumer
    re_path(r'ws/matchmaking/(?P<match_id>\d+)/$', MatchMakingConsumer.as_asgi()),
    re_path(r'ws/tournaments/(?P<tournament_id>\d+)/$', TournamentConsumer.as_asgi()),
]

# only for production to change for deploying
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/backend/friends/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

app_name = 'friends'

urlpatterns = [
    path('', views.friends_overview, name='friends_overview'),
    path('send_request/<int:user_id>/', views.send_friend_request, name='send_friend_request'),
    path('accept_request/<int:request_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('decline_request/<int:request_id>/', views.decline_friend_request, name='decline_friend_request'),
    path('cancel_request/<int:request_id>/', views.cancel_friend_request, name='cancel_friend_request'),
    path('remove_friend/<int:friend_id>/', views.remove_friend, name='remove_friend'),
]

src/backend/game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('', views.quickPlay, name='play'),
    path('solo', views.soloGame, name='solo'),
    # path('multi', views.game_creation, name='multi'),
    # path('multi', views.multiGame, name='multi'),
    # path('multi_scores/<int:game_id>', views.multi_scores, name='multi_scores'),
    # path('play/multi/game', views.test_pong_game, name='multi_game'),
    path('online', views.online_game_creation, name='online'),
    path('error', views.game_error, name='error'),
    path('game/<int:game_id>', views.game_3d, name='real_game'),
    path('end/<int:game_id>/', views.end_game, name='game_end'),
]

src/backend/djangoProject/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.shortcuts import redirect
from dashboard.models import GameHistory
from user.models import UserProfile


def home(request):
    game_histories = GameHistory.objects.order_by('-date_played')[:10]

    # Build a list of game details
    history_data = []
    seen_game_ids = set()
    for history in game_histories:
        if history.game_id in seen_game_ids:
            continue  # Skip duplicate game_id
        seen_game_ids.add(history.game_id)
        game = history.game_object  # Dynamically fetch the related game object
        if game:
            history_data.append({
                'game_id': history.game_id,
                'player_one': game.player_one,
                'player_two': game.player_two,
                'player_one_score': game.player_one_score,
                'player_two_score': game.player_two_score,
                'winner': game.winner,
                'date_played': history.date_played,
                'tx_hash': game.tx_hash,
            })
    profile = None
    if request.user.is_authenticated:
        profile = UserProfile.objects.get(user=request.user)

    context = {
        'user': request.user,
        'game_histories': history_data,
        'profile': profile,
    }

    # If the request is AJAX, return only the content fragment.
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return render(request, 'dashboard/game_history.html', context)

    return render(request, 'djangoProject/home.html', context)


def our_team(request):
    profile = None
    if request.user.is_authenticated:
        profile = UserProfile.objects.get(user=request.user)
    context = {
        'user': request.user,
        'profile': profile,
    }
    # if request.headers.get('x-requested-with') == 'XMLHttpRequest':
    #     return render(request, 'djangoProject/our_team.html', context)
    return render(request, 'djangoProject/our_team.html', context)

src/backend/djangoProject/templates/djangoProject/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

    <link rel="stylesheet" href="{% static 'css/style_main.css' %}">
    <link rel="stylesheet" href="{% static 'css/2falogin.css' %}">
    <link rel="stylesheet" href="{% static 'css/2fasetup.css' %}">
    <link rel="stylesheet" href="{% static 'css/2fadisable.css' %}">
    <!-- Boxicons CSS - On a le droit de load des boxicons cest plus simple non?-->
    <script src="https://kit.fontawesome.com/4cbbdfb3a6.js" crossorigin="anonymous"></script>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel="stylesheet">
    <title>
        {% block title %} The Famous Pong {% endblock %}
    </title>
    {% block head %}{% endblock %}
</head>
<body {% block body_attributes %}{% endblock %}>

<header>
    <div class="header-container">
        <div class="image-text">
        <span class="image">
            <a href="{% url 'home' %}" class="nav-link">
              <i class="fa-solid fa-table-tennis-paddle-ball"></i>
            </a>
        </span>
        </div>
        <div class="login-section">
            {% if user.is_authenticated %}
                <img class=avatar src="{{ profile.avatar.url }}" alt="Profile Image">
                <a> Hi, {{ profile.user.username }} !</a>
                <a href="{% url 'authentication:logout' %}">
                    {% csrf_token %}
                    <i class='bx bx-log-out'></i>
                </a>
            {% else %}
                <a href="{% url 'authentication:register' %}" title="register">Register</a>
                <a href="{% url 'authentication:login' %}" title="login">Login</a>
            {% endif %}
        </div>
    </div>
    <div class="diffuse-circle circle-2"></div>

</header>

<nav class="sidebar">
    <div class="menu-container">
        <div class="menu-bar">
            <li class="nav-links">
                <a href="{% url 'home' %}" class="nav-link navbar-link" data-page="home" title="Home">
                    <i class='bx bxs-home-alt-2 icon'></i>
                </a>
                <a href="{% url 'dashboard:leaderboard' %}" class="nav-link navbar-link" data-page="leaderboard"
                   title="Leaderboard">
                    <i class='bx bxs-trophy icon'></i>
                </a>
                {% if user.is_authenticated %}
                    <a href="{% url 'dashboard:dashboard' %}" class="nav-link navbar-link" data-page="dashboard"
                       title="Dashboard">
                        <i class='bx bxs-face icon'></i>
                    </a>
                    <a href="{% url 'friends:friends_overview' %}" class="nav-link navbar-link" data-page="friends"
                       title="Friends">
                        <i class='bx bxs-heart icon'></i>
                    </a>
                {% endif %}
                <a href="{% url 'game:play' %}" class="nav-link navbar-link" data-page="play" title="Play">
                    <i class='bx bxs-rocket icon'></i>
                </a>
                <a href="{% url 'our_team' %}" class="nav-link navbar-link" data-page="our_team" title="Our Team">
                    <i class='bx bxl-github icon'></i>
                </a>
            </li>
        </div>
        <div class="bottom-content">
            <li class="mode">
                <div class="moon-sun">
                    <i class='bx bx-moon moon'></i>
                    <i class='bx bx-sun sun'></i>
                </div>
                <div class="toggle-switch">
                    <span class="switch"></span>
                </div>
            </li>
        </div>
    </div>
</nav>


<section class="home">
    <main id="content">
        {% block content %}
            <div class="home_gameHistory_container">
                {% include 'dashboard/game_history.html' %}
            </div>
        {% endblock %}
    </main>
</section>

<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/spa.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

src/backend/djangoProject/templates/djangoProject/our_team.html
{% extends 'djangoProject/home.html' %}
{% block title %}Our Team{% endblock %}
{% block body_attributes %}data-active-page="our_team"{% endblock %}
{% load static %}
{% block content %}
    <h2>Our team</h2>
    <div class="our-team-container">
        <div class="elo-container container">
            <a href="https://github.com/Eyzou" target="_blank">Elodie</a>

        </div>
        <div class="eliot-container container">
            <a href="https://github.com/Erio6" target="_blank">Eliot</a>

        </div>
        <div class="antho-container container">
            <a href="https://github.com/Norias1011" target="_blank">Anthony</a>

        </div>
        <div class="mehdi-container container">
            <a href="https://github.com/z3msta" target="_blank">Mehdi</a>

        </div>
        <div class="diffuse-circle circle-1"></div>
    </div>
{% endblock %}