src/backend/API/urls.py
from django.urls import path
from . import views
from .views import CheckTransactionStatus

app_name = 'API'

urlpatterns = [
    path('score', views.game_update, name='game_update'),
    path('scorehistory', views.GameHistoryView.as_view(), name='score_history_api'),
    path('check_transaction_status/<int:game_id>/', views.CheckTransactionStatus.as_view(), name='check_transaction_status'),
]

src/backend/djangoProject/urls.py
from django.urls import path, include, re_path
from two_factor.urls import urlpatterns as tf_urls
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

import matchMaking
from game.consumers import GameConsumer
from matchMaking.consumers import MatchMakingConsumer
from tournaments.consumers import TournamentConsumer
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

"""
URL configuration for djangoProject project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.urls import path, include

app_name = 'djangoProject'

urlpatterns = [
    path('', views.home, name="home"),
    path('our_team', views.our_team, name="our_team"),
    path('', include(tf_urls)),  # Admin route
    path('admin/', admin.site.urls),  # Admin route
    path('game/', include('game.urls')),
    path('auth/', include('authentication.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('user/', include('user.urls')),
    path('friends/', include('friends.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('API.urls')),
    path('leaderboard/', include('dashboard.urls')),
    path('matchMaking', include('matchMaking.urls')),
    path('tournament/', include('tournaments.urls')),
]

websocket_urlpatterns = [
    re_path(r'ws/game/(?P<room_id>\d+)/$', GameConsumer.as_asgi()), # Map WebSocket path to consumer
    re_path(r'ws/matchmaking/(?P<match_id>\d+)/$', MatchMakingConsumer.as_asgi()),
    re_path(r'ws/tournaments/(?P<tournament_id>\d+)/$', TournamentConsumer.as_asgi()),
]

# only for production to change for deploying
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/backend/game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('', views.quickPlay, name='play'),
    path('solo', views.soloGame, name='solo'),
    # path('multi', views.game_creation, name='multi'),
    # path('multi', views.multiGame, name='multi'),
    # path('multi_scores/<int:game_id>', views.multi_scores, name='multi_scores'),
    # path('play/multi/game', views.test_pong_game, name='multi_game'),
    path('online', views.online_game_creation, name='online'),
    path('error', views.game_error, name='error'),
    path('game/<int:game_id>', views.game_3d, name='real_game'),
    path('end/<int:game_id>/', views.end_game, name='game_end'),
]

src/backend/matchMaking/urls.py
from django.urls import path
from . import views

app_name = 'matchMaking'

urlpatterns = [
    path('matchmaking', views.waiting_view, name='matchmaking'),
]

src/backend/tournaments/urls.py
from django.urls import path
from . import views

app_name = 'tournaments'

urlpatterns = [
    path('', views.tournaments_home, name='tournaments'),
    path('create', views.create_tournament, name='create_tournament'),
    path('join', views.join_tournament, name='join_tournament'),
    path('waiting-room/<int:tournament_id>/', views.tournament_waiting_room, name='waiting_room'),
    path('cancel/<int:tournament_id>/', views.cancel_tournament, name='cancel_tournament'),
    path('leave/<int:tournament_id>/', views.leave_tournament, name='leave_tournament'),
    path('start/<int:tournament_id>/', views.start_tournament, name='start_tournament'),
    path('tree/<int:tournament_id>/', views.tournament_tree_view, name='tournament_tree'),
    path('tournament_tree_data/<int:tournament_id>/', views.tournament_tree_data, name='tournament_tree_data'),
]

src/backend/game/models.py
from django.contrib.auth.models import User
from django.db import models
from user.models import UserProfile
from django.contrib.contenttypes.fields import GenericRelation

# Create your models here.
class Game(models.Model):
    game_histories = GenericRelation('dashboard.GameHistory',
                                     content_type_field='game_type',
                                     object_id_field='game_id')
    player_one = models.ForeignKey(UserProfile, related_name='player_one_games', on_delete=models.CASCADE)
    player_two = models.ForeignKey(UserProfile, related_name='player_two_games', null=True, blank=True, on_delete=models.CASCADE)
    winner = models.ForeignKey(UserProfile, related_name='winner_games', null=True, on_delete=models.SET_NULL)
    looser = models.ForeignKey(UserProfile, related_name='looser_games', null=True, on_delete=models.SET_NULL)
    player_one_score = models.IntegerField(default=0, null=True, blank=True)
    player_two_score = models.IntegerField(default=0, null=True, blank=True)
    winner_score = models.IntegerField(default=0, null=True, blank=True)
    looser_score = models.IntegerField(default=0, null=True, blank=True)
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(null=True)
    is_completed = models.BooleanField(default=False)
    tx_hash = models.CharField(max_length=66, blank=True, null=True)
    is_recorded_on_blockchain = models.BooleanField(default=False)
    type_of_game = models.CharField(max_length=20, choices=[('multiplayer', 'Multiplayer'), ('solo_IA_easy', 'Solo IA Easy'), ('solo_IA_medium', 'Solo IA Medium'), ('solo_IA_hard', 'Solo IA Hard'), ('solo_player', 'Solo Player'), ('tournament', 'Tournament')], default='multiplayer')

    def __str__(self):
        if self.player_two:
            return f'{self.player_one.display_name} vs {self.player_two.display_name}'
        else:
            return f'{self.player_one.display_name} is waiting an opponent in {self.id}'

class SoloGame(models.Model):
    player_solo = models.ForeignKey(UserProfile, related_name='player_one_games_solo', on_delete=models.CASCADE)
    winner = models.ForeignKey(UserProfile, related_name='winner_games_solo', null=True, on_delete=models.CASCADE)
    looser = models.ForeignKey(UserProfile, related_name='looser_games_solo', null=True, on_delete=models.CASCADE)
    player_solo_score = models.IntegerField(default=0)
    IA_score = models.IntegerField(default=0)
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(null=True)
    is_completed = models.BooleanField(default=False)

src/backend/game/forms.py
from django import forms
from .models import Game
from user.models import UserProfile


class GameCreationForm(forms.Form):
    # player_side = forms.ChoiceField(choices=[(1, "Player One (Left)"), (2, "Player Two (Right)")], label="Choose Your Side", widget=forms.RadioSelect)
    game_type = forms.ChoiceField(
        choices=[('solo_IA_easy', 'Easy IA'), ('solo_IA_medium', 'Medium IA'), ('solo_IA_hard', 'Hard IA'),
                 ('solo_player', 'Player 2')], label="Choose Your Game Type", widget=forms.Select)

src/backend/game/views.py
from contextlib import nullcontext
from xxlimited_35 import error

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.http import HttpResponseForbidden
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated

from .forms import GameCreationForm
from .models import Game
from user.models import UserProfile
from asgiref.sync import sync_to_async


def quickPlay(request):
    profile = None
    if request.user.is_authenticated:
        profile = UserProfile.objects.get(user=request.user)
    return render(request, 'game/playmode.html', {"profile": profile})


# @api_view(["GET", "POST"])
# @permission_classes([IsAuthenticated])
@login_required
def soloGame(request):
    profile = UserProfile.objects.get(user=request.user)
    if request.method == 'POST':
        print(request.POST)
        form = GameCreationForm(request.POST)
        if form.is_valid():
            print("valid")
            # player_side = form.cleaned_data['player_side']
            game_type = form.cleaned_data['game_type']

            try:
                player_profile = request.user.userprofile
            except UserProfile.DoesNotExist:
                return redirect('user:edit_user_profile', username=request.user.username)

            game = Game.objects.create(player_one=player_profile, is_completed=False, type_of_game=game_type)

            return redirect(reverse('game:real_game', kwargs={'game_id': game.id}))
        else:
            print(form.errors)
    else:
        form = GameCreationForm()
    return render(request, 'game/sologame.html', {'form': form, 'profile': profile})


# @api_view(["GET"])
# @permission_classes([IsAuthenticated])
@login_required
def online_game_creation(request):
    # print(request.user.id, UserProfile.objects.get(id=request.user.id))
    profile = None
    if request.user.is_authenticated:
        profile = UserProfile.objects.get(user=request.user)
    games = Game.objects.filter(is_completed=False, type_of_game="multiplayer").all()
    return render(request, 'game/online.html', {"games": games, "profile": profile})


# @api_view(["GET"])
# @permission_classes([IsAuthenticated])
@login_required
def game_3d(request, game_id):
    if not request.user.is_authenticated:
        return redirect("authentication:login")

    profile = UserProfile.objects.get(user=request.user)
    if not Game.objects.filter(id=game_id).exists():
        print("Game does not exist", game_id)
        return redirect('/')
    return render(request, 'game/threejs.html', {"profile": profile})


# @api_view(["GET"])
# @permission_classes([IsAuthenticated])
@login_required
def game_error(request):
    return render(request, 'game/error.html', {})


# @api_view(["GET", "POST"])
# @permission_classes([IsAuthenticated])
@login_required
def end_game(request, game_id):
    game = get_object_or_404(Game, id=game_id)
    winner_user = game.winner.user
    looser_user = game.looser.user
    current_user_id = request.user.id
    profile = UserProfile.objects.get(user=request.user)

    # if current_user_id != winner_user.id and current_user_id != looser_user.id:
    #     content = render_to_string('game/unauthorized.html')
    #     return HttpResponseForbidden(content)

    context = {
        'game': game,
        'winner': game.winner,
        'looser': game.looser,
        'winner_score': game.winner_score,
        'looser_score': game.looser_score,
        'tx_hash': game.tx_hash,
        'profile': profile,
    }

    # Render the template asynchronously
    return render(request, 'game/end_game.html', context)

src/backend/game/templates/game/end_game.html
{% extends 'djangoProject/home.html' %}
{% block title %}End Game{% endblock %}
{% block body_attributes %}data-active-page="play"{% endblock %}
{% block head %}
    <script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.6.0/dist/confetti.browser.min.js"></script>
{% endblock %}
{% block content %}
    <div class="container-end-game">
        {% if user == winner.user %}
            <div id="celebration">
                <h2>Congratulations, You Won!</h2>
            </div>
        {% elif user == looser.user %}
            <div id="loser">
                <h2>You Lost!</h2>
            </div>
        {% endif %}

        {% if is_tournament %}
            <p>ref to the tournament tree to ADD </p>
        {% endif %}

        <p><strong>Winner: </strong> {{ winner.user.username }}</p>
        <p><strong>Loser: </strong> {{ looser.user.username }}</p>
        <p><strong>Final Score: </strong> {{ winner_score }} - {{ looser_score }}</p>
        <div class="diffuse-circle circle-1"></div>
    </div>

    <script>
        // Juste les confettis
        const gameId = "{{ game.id }}";
        if (document.getElementById("celebration")) {
            confetti({
                particleCount: 1000,
                spread: 100,
                origin: {x: 0.55, y: 0.6}
            });
        }
    </script>

    <!--    <script>-->
    <!--        setTimeout(function() {-->
    <!--            window.location.href = "{% url 'home' %}";-->
    <!--        }, 10000); -->
    <!--    </script>-->
{% endblock %}

src/backend/game/templates/game/error.html
{% extends 'djangoProject/home.html' %}
{% block title %}Error{% endblock %}
{% block body_attributes %}data-active-page="play"{% endblock %}

{% load static %}

{% block content %}
    <div class="error-container">
        <h1>An error occurred</h1>
        <p>Please try again later.</p>
        <a class="btn" href="{% url 'home' %}">Go home</a>
    </div>
{% endblock %}

src/backend/game/templates/game/multisearch.html
{% extends 'djangoProject/home.html' %}
{% block title %}Multiplayer{% endblock %}
{% block body_attributes %}data-active-page="play"{% endblock %}
{% block content %}
    <div class="multiplayer_search">
        <h1 class="title_multi_search"> Find your opponent </h1>
        <a href="{% url 'matchMaking:matchmaking' %}" class="nav-link" class="button_multi_search">New Game</a>
    </div>
{% endblock %}

src/backend/game/templates/game/online.html
{% extends 'djangoProject/home.html' %}
{% block title %}Quick Play{% endblock %}
{% block body_attributes %}data-active-page="play"{% endblock %}
{% block content %}
    <div class="online-content">
        <h1>Online Game</h1>
        <div class="online-container">
            {% for game in games %}
                <div class="link-container">
                    <a class="game-online" href="/game/game/{{ game.id }}">
                        <img src="{{ game.player_one.avatar.url }}" alt="profile picture">
                        {{ game.player_one.display_name }}
                        vs {{ game.player_two.display_name }}
                        <img src="{{ game.player_two.avatar.url }}" alt="profile picture"></a>
                    <a class="spectate btn" href="/game/game/{{ game.id }}">Spectate <i class="fa-solid fa-eye"></i></a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

src/backend/game/templates/game/playmode.html
{% extends 'djangoProject/home.html' %}
{% block title %}Quick Play{% endblock %}
{% block body_attributes %}data-active-page="play"{% endblock %}
{% block content %}
    <div class="grid-container">
        <a href="{% url 'matchMaking:matchmaking' %}" class="online-game game-container">
            <div class="online-game-container">
                <h1>Online game</h1>
                <p>Play one game of Pong against an opponent and get elo points if you win.</p>
            </div>
        </a>
        <a href="{% url 'game:solo' %}" class="small-game solo-game game-container nav-link">
            <h1>Local Game</h1>
            <p>Play a local game against a player on the same device or play against one of the three AI available.</p>
        </a>
        <a href="{% url 'tournaments:tournaments' %}" class="small-game tournament-game game-container">
            <h1>Tournament</h1>
            <p>Create or join a tournament to fight against at least 4 opponents in a bracket-based tournament.</p>
        </a>
        <a href="{% url 'game:online' %}" class="small-game spectate-game game-container nav-link">
            <h1>Spectate Game</h1>
            <p>Spectate any online game and see how bad Lucas is.</p>
        </a>
    </div>

    {% if messages %}
        <script>
            {% for message in messages %}
                alert("{{ message }}");
            {% endfor %}
        </script>
    {% endif %}
{% endblock %}

src/backend/game/templates/game/sologame.html
{% extends 'djangoProject/home.html' %}
{% block title %}Local Game{% endblock %}
{% block body_attributes %}data-active-page="play"{% endblock %}
{% block content %}
    <div class="solo-game-container">
        <h2 class="solo-game-header">Start a Local Game</h2>
        <form method="post" class="solo-game-form">
            {% csrf_token %}
            <p>{{ form.game_type.label }}</p>
            {{ form.game_type }}

            {{ form.player_profile }}  <!-- Hidden input field -->

            <button class="primary-btn" type="submit">Start Game</button>
        </form>
    </div>
{% endblock %}

src/backend/game/templates/game/threejs.html
{% extends 'djangoProject/home.html' %}
{% block title %}Quick Play{% endblock %}
{% load static %}
{% block body_attributes %}data-active-page="play"{% endblock %}

{% block content %}
    <div id="scene-container">
    </div>

    <script type="importmap">
        {
          "imports": {
            "three": "https://cdn.jsdelivr.net/npm/three@v0.171.0/build/three.module.js",
            "three/addons/": "https://cdn.jsdelivr.net/npm/three@v0.171.0/examples/jsm/"
          }
        }
    </script>
    <script type="module" src="{% static 'js/threejs/main.js' %}"></script>
    <style>
        #scene-container {
            position: absolute;
            width: 100%;
            height: 100%;
            min-height: 800px;
        }

        body {
            overflow: hidden;
        }
    </style>
{% endblock %}