src/backend/API/urls.py
from django.urls import path
from . import views
from .views import CheckTransactionStatus

app_name = 'API'

urlpatterns = [
    path('score', views.game_update, name='game_update'),
    path('scorehistory', views.GameHistoryView.as_view(), name='score_history_api'),
    path('check_transaction_status/<int:game_id>/', views.CheckTransactionStatus.as_view(), name='check_transaction_status'),
]

src/backend/djangoProject/urls.py
from django.urls import path, include, re_path
from two_factor.urls import urlpatterns as tf_urls
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

import matchMaking
from game.consumers import GameConsumer
from matchMaking.consumers import MatchMakingConsumer
from tournaments.consumers import TournamentConsumer
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

"""
URL configuration for djangoProject project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.urls import path, include

app_name = 'djangoProject'

urlpatterns = [
    path('', views.home, name="home"),
    path('our_team', views.our_team, name="our_team"),
    path('', include(tf_urls)),  # Admin route
    path('admin/', admin.site.urls),  # Admin route
    path('game/', include('game.urls')),
    path('auth/', include('authentication.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('user/', include('user.urls')),
    path('friends/', include('friends.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('API.urls')),
    path('leaderboard/', include('dashboard.urls')),
    path('matchMaking', include('matchMaking.urls')),
    path('tournament/', include('tournaments.urls')),
]

websocket_urlpatterns = [
    re_path(r'ws/game/(?P<room_id>\d+)/$', GameConsumer.as_asgi()), # Map WebSocket path to consumer
    re_path(r'ws/matchmaking/(?P<match_id>\d+)/$', MatchMakingConsumer.as_asgi()),
    re_path(r'ws/tournaments/(?P<tournament_id>\d+)/$', TournamentConsumer.as_asgi()),
]

# only for production to change for deploying
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/backend/friends/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

app_name = 'friends'

urlpatterns = [
    path('', views.friends_overview, name='friends_overview'),
    path('send_request/<int:user_id>/', views.send_friend_request, name='send_friend_request'),
    path('accept_request/<int:request_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('decline_request/<int:request_id>/', views.decline_friend_request, name='decline_friend_request'),
    path('cancel_request/<int:request_id>/', views.cancel_friend_request, name='cancel_friend_request'),
    path('remove_friend/<int:friend_id>/', views.remove_friend, name='remove_friend'),
]

src/backend/friends/models.py
from django.db import models
from django.core.exceptions import ValidationError
from user.models import UserProfile


class FriendList(models.Model):
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE, related_name='friend_list')
    friends = models.ManyToManyField(UserProfile, blank=True, related_name='friends')

    def __str__(self):
        return self.user.user.username

    def add_friend(self, account):
        if not account in self.friends.all():
            self.friends.add(account)

    def remove_friend(self, account):
        if account in self.friends.all():
            self.friends.remove(account)

    def unfriend(self, removee):
        remover_friends_list = self
        remover_friends_list.remove_friend(removee)
        friends_list = FriendList.objects.get(user=removee)
        friends_list.remove_friend(self.user)

    def is_mutual_friend(self, friend):
        if friend in self.friends.all():
            return True


class FriendRequest(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('accepted', 'Accepted'),
        ('declined', 'Declined')
    )
    sender = models.ForeignKey(UserProfile, related_name='sender', on_delete=models.CASCADE)
    receiver = models.ForeignKey(UserProfile, related_name='receiver', on_delete=models.CASCADE)
    status = models.CharField(choices=STATUS_CHOICES, default='Pending')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"From {self.sender.user.username} to {self.receiver.user.username}"

    def save(self, *args, **kwargs):
        if self.sender == self.receiver:
            raise ValidationError("Users cannot send friend requests to themselves.")
        super().save(*args, **kwargs)

    def accept(self):
        receiver_friend_list = FriendList.objects.get(user=self.receiver)
        if receiver_friend_list:
            receiver_friend_list.add_friend(self.sender)
            sender_friend_list = FriendList.objects.get(user=self.sender)
            if sender_friend_list:
                sender_friend_list.add_friend(self.receiver)
                self.status = 'Accepted'
                self.save()

    def decline(self):
        self.status = 'Declined'
        self.save()

    def cancel(self):
        self.status = 'Declined'
        self.save()



# Create your models here.

src/backend/friends/forms.py
from django import forms

src/backend/friends/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import FriendRequest, FriendList
from django.contrib import messages
from django.shortcuts import render
from django.db.models import Q
from user.models import UserProfile

# Create your views here.

@login_required
def friends_overview(request):
    userprofile = request.user.userprofile
    friend_list = get_object_or_404(FriendList, user=userprofile)
    friends = friend_list.friends.all()
    incoming_requests = FriendRequest.objects.filter(receiver=userprofile, status='Pending')
    outgoing_requests = FriendRequest.objects.filter(sender=userprofile, status='Pending')

    query = request.GET.get('q', '')
    search_results = []
    if query:
        search_results = UserProfile.objects.filter(
            user__username__icontains=query
        ).exclude(
            id=userprofile.id
        ).exclude(
            Q(friend_list__friends=userprofile) |
            Q(receiver__sender=userprofile, receiver__status='pending') |
            Q(sender__receiver=userprofile, sender__status='pending')
        ).distinct()
    profile = None
    if request.user.is_authenticated:
        profile = UserProfile.objects.get(user=request.user)

    context = {
        'friends': friends,
        'incoming_requests': incoming_requests,
        'outgoing_requests': outgoing_requests,
        'search_results': search_results,
        'query': query,
        'profile': profile,
    }
    return render(request, 'friends/friends.html', context)


@login_required
def send_friend_request(request, user_id):
    if request.method == 'POST':
        sender = request.user.userprofile
        receiver = get_object_or_404(UserProfile, id=user_id)

        if sender == receiver:
            messages.error(request, "You cannot sent a friend request.")
            return redirect('friends:friends_overview')

        existing_request = FriendRequest.objects.filter(
            sender=sender, receiver=receiver, status='Pending'
        ).exists()

        existing_friendship = FriendList.objects.filter(
            Q(user=sender, friends=receiver) | Q(user=receiver, friends=sender)
        ).exists()

        if existing_request:
            messages.info(request, "Friend request is pending.")
        elif existing_friendship:
            messages.info(request, "Your are already friends")
        else:
            FriendRequest.objects.create(sender=sender, receiver=receiver)
            messages.success(request, f'Friend request sent to {receiver.user.username}.')

    return redirect('friends:friends_overview')

@login_required
def accept_friend_request(request, request_id):
    friend_request = get_object_or_404(FriendRequest, id=request_id, receiver=request.user.userprofile,
                                       status='Pending')
    if request.method == 'POST':
        friend_request.accept()
        messages.success(request, f'You are now friend with {friend_request.sender.user.userprofile}.')
    return redirect('friends:friends_overview')


@login_required
def decline_friend_request(request, request_id):
    friend_request = get_object_or_404(FriendRequest, id=request_id, receiver=request.user.userprofile,
                                       status='Pending')
    if request.method == 'POST':
        friend_request.decline()
        messages.info(request, f'Friend request sent to{friend_request.sender.user.userprofile} declined.')
    return redirect('friends:friends_overview')


@login_required
def cancel_friend_request(request, request_id):
    friend_request = get_object_or_404(FriendRequest, id=request_id, sender=request.user.userprofile, status='Pending')
    if request.method == 'POST':
        friend_request.cancel()
        messages.info(request, f'Friend request sent to {friend_request.receiver.user.userprofile} cancelled.')
    return redirect('friends:friends_overview')


@login_required
def remove_friend(request, friend_id):
    friend = get_object_or_404(UserProfile, id=friend_id)
    friend_list = get_object_or_404(FriendList, user=request.user.userprofile)
    if request.method == 'POST':
        friend_list.remove_friend(friend)
        other_friend_list = get_object_or_404(FriendList, user=friend)
        other_friend_list.remove_friend(friend_list.user)
        messages.info(request, f'Friend {friend.user.userprofile} Deleted.')
    return redirect('friends:friends_overview')

src/backend/friends/templates/friends/friends.html
{% extends 'djangoProject/home.html' %}

{% load static %}
{% block body_attributes %}data-active-page="friends"{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static 'flags/sprite-hq.css' %}">
    <h2>My Friends</h2>
    <div class="my-friends">
        <div class="add-friends">
            <div class="search">
                <h2>Add a Friend</h2>
                <form class="form-link" method="GET" action="{% url 'friends:friends_overview' %}">
                    <input class="input" type="text" name="q" value="{{ query }}" placeholder="Search for users...">
                    <button class="btn" type="submit">Search</button>
                </form>
            </div>
            <div class="form-result">
                {% if query %}
                    <h3>{{ search_results.count }} result(s) found</h3>
                {% else %}
                    <h3>Friends search</h3>
                {% endif %}
                <div class="sep"></div>
                <div class="friends-container">
                    {% if query %}
                        {% if search_results %}
                            <ul>
                                {% for user in search_results %}
                                    <li class="friend-item">
                                        <div class="profile">
                                            <div class="img-container">
                                                <img src="{{ user.avatar.url }}" alt="">
                                            </div>
                                            <p>{{ user.user.username }}</p>
                                        </div>
                                        <div class="country">
                                            <div class="img-container">
                                                <img src="{{ user.country.flag }}"
                                                     alt="{{ user.country.name }}">
                                            </div>
                                            <p>{{ user.country.name }}</p>
                                        </div>
                                        <form class="form-link"
                                              action="{% url 'friends:send_friend_request' user.user.id %}"
                                              method="POST">
                                            {% csrf_token %}
                                            <button class="accept" type="submit">Add Friend
                                                <span>
                                                <img src=" {% static 'img/accept.png' %}" alt="">
                                            </span>
                                            </button>
                                        </form>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <p> No users found for "{{ query }}".</p>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
            <div class="pending">
                <h3>Pending invitation sent</h3>
                <div class="sep"></div>
                <div class="friends-container">
                    <ul>
                        {% for request in outgoing_requests %}
                            <li class="friend-item">
                                <div class="profile">
                                    <div class="img-container">
                                        <img src="{{ request.receiver.avatar.url }}" alt="">
                                    </div>
                                    <p>{{ request.receiver.user.username }}</p>
                                </div>
                                <div class="country">
                                    <div class="img-container">
                                        <img src="{{ request.receiver.country.flag }}"
                                             alt="{{ request.receiver.country.name }}">
                                    </div>
                                    <p>{{ request.receiver.country.name }}</p>
                                </div>
                                <form class="form-link" action="{% url 'friends:cancel_friend_request' request.id %}"
                                      method="POST">
                                    {% csrf_token %}
                                    <button class="accept" type="submit">Cancel request
                                        <span>
                                                <img src=" {% static 'img/deny.png' %}" alt="">
                                            </span>
                                    </button>
                                </form>
                            </li>
                            {% empty %}
                            <li class="list-group-item">No invitation sent.</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>


        </div>
        <div class="friend-list"><h2>Friend List</h2>
            {% if friends %}
                <ul>
                    {% for friend in friends %}
                        <li class="friend-item">
                            <div class="profile">
                                <div class="img-container">
                                    <span class="status-dot {% if friend.user.userprofile.is_online %} online {% else %} offline {% endif %}"></span>
                                    <img src="{{ friend.avatar.url }}" alt="">
                                </div>
                                <p>{{ friend.user.username }}</p>
                            </div>
                            <form class="form-link" action="{% url 'friends:remove_friend' friend.id %}"
                                  method="POST">
                                {% csrf_token %}
                                <button class="accept" type="submit">Remove
                                    <span>
                                        <img src=" {% static 'img/deny.png' %}" alt="">
                                    </span>
                                </button>
                            </form>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>You have no friends.</p>
            {% endif %}
        </div>
        <div class="friend-request-received">
            <h3>Friend request received</h3>
            <ul>
                {% for request in incoming_requests %}
                    <li class="friend-item">
                        <div class="profile">
                            <div class="img-container">
                                <img src="{{ request.sender.avatar.url }}" alt="">
                            </div>
                            <p>{{ request.sender.user.username }}</p>
                        </div>
                        <form class="form-link" action="{% url 'friends:accept_friend_request' request.id %}"
                              method="POST">
                            {% csrf_token %}
                            <button class="accept" type="submit">Accept
                                <span>
                                        <img src=" {% static 'img/accept.png' %}" alt="">
                                    </span>
                            </button>
                        </form>
                        <form class="form-link" action="{% url 'friends:decline_friend_request' request.id %}"
                              method="POST">
                            {% csrf_token %}
                            <button class="accept" type="submit">Deny
                                <span>
                                        <img src=" {% static 'img/deny.png' %}" alt="">
                                    </span>
                            </button>
                        </form>
                    </li>
                    {% empty %}
                    <li class="list-group-item">No incoming friend requests.</li>
                {% endfor %}
            </ul>
        </div>

    </div>
    <div class="diffuse-circle circle-1"></div>
{% endblock %}