src/backend/API/urls.py
from django.urls import path
from . import views
from .views import CheckTransactionStatus

app_name = 'API'

urlpatterns = [
    path('score', views.game_update, name='game_update'),
    path('scorehistory', views.GameHistoryView.as_view(), name='score_history_api'),
    path('check_transaction_status/<int:game_id>/', views.CheckTransactionStatus.as_view(), name='check_transaction_status'),
]

src/backend/djangoProject/urls.py
from django.urls import path, include, re_path
from two_factor.urls import urlpatterns as tf_urls
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

import matchMaking
from game.consumers import GameConsumer
from matchMaking.consumers import MatchMakingConsumer
from tournaments.consumers import TournamentConsumer
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

"""
URL configuration for djangoProject project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.urls import path, include

app_name = 'djangoProject'

urlpatterns = [
    path('', views.home, name="home"),
    path('our_team', views.our_team, name="our_team"),
    path('', include(tf_urls)),  # Admin route
    path('admin/', admin.site.urls),  # Admin route
    path('game/', include('game.urls')),
    path('auth/', include('authentication.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('user/', include('user.urls')),
    path('friends/', include('friends.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('API.urls')),
    path('leaderboard/', include('dashboard.urls')),
    path('matchMaking', include('matchMaking.urls')),
    path('tournament/', include('tournaments.urls')),
]

websocket_urlpatterns = [
    re_path(r'ws/game/(?P<room_id>\d+)/$', GameConsumer.as_asgi()), # Map WebSocket path to consumer
    re_path(r'ws/matchmaking/(?P<match_id>\d+)/$', MatchMakingConsumer.as_asgi()),
    re_path(r'ws/tournaments/(?P<tournament_id>\d+)/$', TournamentConsumer.as_asgi()),
]

# only for production to change for deploying
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/backend/tournaments/urls.py
from django.urls import path
from . import views

app_name = 'tournaments'

urlpatterns = [
    path('', views.tournaments_home, name='tournaments'),
    path('create', views.create_tournament, name='create_tournament'),
    path('join', views.join_tournament, name='join_tournament'),
    path('waiting-room/<int:tournament_id>/', views.tournament_waiting_room, name='waiting_room'),
    path('cancel/<int:tournament_id>/', views.cancel_tournament, name='cancel_tournament'),
    path('leave/<int:tournament_id>/', views.leave_tournament, name='leave_tournament'),
    path('start/<int:tournament_id>/', views.start_tournament, name='start_tournament'),
    path('tree/<int:tournament_id>/', views.tournament_tree_view, name='tournament_tree'),
    path('tournament_tree_data/<int:tournament_id>/', views.tournament_tree_data, name='tournament_tree_data'),
]

src/backend/tournaments/models.py
from django.contrib.auth.models import User
from django.db import models
from user.models import UserProfile
from game.models import Game

# Create your models here.
class Tournament(models.Model):
    name = models.CharField(max_length=100)
    start_date = models.DateTimeField(auto_now_add=True)
    end_date = models.DateTimeField(null=True)
    created_by = models.ForeignKey(UserProfile, related_name='tournament_creator' ,on_delete=models.CASCADE)
    tournament_code_join = models.CharField(max_length=4, unique=True)
    players = models.ManyToManyField(UserProfile, through='TournamentPlayer')
    status = models.CharField(
        max_length=20,
        choices=[('waiting', 'Waiting for players'), ('ongoing', 'Ongoing'), ('completed', 'Completed')],
        default='waiting'
    )
    def __str__(self):
        return self.name

class TournamentPlayer(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    player = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    is_eliminated = models.BooleanField(default=False)
    round_reached = models.PositiveIntegerField(default=0)
    def __str__(self):
        return f"{self.player.display_name} in {self.tournament.name}"

class TournamentGame(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    player_one = models.ForeignKey(TournamentPlayer, related_name='tournament_player_one' ,on_delete=models.CASCADE, null=True, blank=True)
    player_two = models.ForeignKey(TournamentPlayer, related_name='tournament_player_two',on_delete=models.CASCADE, null=True, blank=True)
    game = models.ForeignKey(Game, on_delete=models.CASCADE, null=True, blank=True)
    winner = models.ForeignKey(TournamentPlayer, related_name='game_winner', null=True, on_delete=models.SET_NULL)
    round_number = models.PositiveIntegerField(default=0)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, related_name='child_games')

    

src/backend/tournaments/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.utils.crypto import get_random_string
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from django.db import transaction
from django.http import JsonResponse
from math import ceil, log2

from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated

from .utils import create_games, generate_links, assign_parent_child_relationships
from user.models import UserProfile

from tournaments.models import Tournament, TournamentPlayer, TournamentGame

import random
import json


# Create your views here.

def tournaments_home(request):
    profile = UserProfile.objects.get(user=request.user)
    return render(request, 'tournaments/tournament_home.html', {'profile': profile})


# @api_view(["GET"])
# @permission_classes([IsAuthenticated])
@login_required
def create_tournament(request):
    profile = UserProfile.objects.get(user=request.user)
    if request.method == 'POST':
        name = request.POST['name']
        code = get_random_string(4)

        tournament = Tournament.objects.create(
            name=name,
            created_by=request.user.userprofile,
            tournament_code_join=code
        )
        TournamentPlayer.objects.create(tournament=tournament, player=request.user.userprofile)
        print("*************Tournament ID : ")
        print(tournament.id)
        return redirect('tournaments:waiting_room', tournament_id=tournament.id)

    return render(request, 'tournaments/create_tournament.html', {'profile': profile})


# @api_view(["GET"])
# @permission_classes([IsAuthenticated])
@login_required
def join_tournament(request):
    profile = UserProfile.objects.get(user=request.user)
    if request.method == 'POST':
        code = request.POST['code']

        tournament = Tournament.objects.filter(tournament_code_join=code, status='waiting').first()
        if tournament:
            if TournamentPlayer.objects.filter(tournament=tournament, player=request.user.userprofile).exists():
                return redirect(request, 'tournaments:waiting_room', tournament_id=tournament.id)
            TournamentPlayer.objects.create(tournament=tournament, player=request.user.userprofile)
            return redirect('tournaments:waiting_room', tournament_id=tournament.id)
        else:
            return render(request, 'tournaments/join_tournament.html',
                          {'error': 'Invalid tournament code or tournament has already started.'})

    return render(request, 'tournaments/join_tournament.html', {'profile': profile})


# @api_view(["GET"])
# @permission_classes([IsAuthenticated])
@login_required
def tournament_waiting_room(request, tournament_id):
    profile = UserProfile.objects.get(user=request.user)
    tournament = get_object_or_404(Tournament, id=tournament_id)
    print("*************Tournament ID 2: ")
    print(tournament.id)
    players = TournamentPlayer.objects.filter(tournament=tournament)
    return render(request, 'tournaments/tournament_waiting_room.html', {
        'tournament': tournament,
        'players': players,
        'current_user': request.user,
        'profile': profile,
    })


# @api_view(["GET"])
# @permission_classes([IsAuthenticated])
@login_required
def cancel_tournament(request, tournament_id):
    tournament = get_object_or_404(Tournament, id=tournament_id, created_by=request.user.userprofile)

    group_name = f'tournament_{tournament.id}'
    channel_layer = get_channel_layer()
    async_to_sync(channel_layer.group_send)(
        group_name,
        {
            'type': 'handle_tournament_cancel',
        }
    )

    tournament.delete()
    return redirect('tournaments:tournaments')


# @api_view(["GET"])
# @permission_classes([IsAuthenticated])
@login_required
def leave_tournament(request, tournament_id):
    tournament = get_object_or_404(Tournament, id=tournament_id)
    player = TournamentPlayer.objects.filter(tournament=tournament, player=request.user.userprofile).first()

    # Make sure that the creator cannot leave the tournament, he can only cancel it
    if player:
        if tournament.created_by == request.user.userprofile:
            return redirect('tournaments:waiting_room', tournament_id=tournament.id)

        group_name = f'tournament_{tournament.id}'
        channel_layer = get_channel_layer()
        async_to_sync(channel_layer.group_send)(
            group_name,
            {
                'type': 'handle_player_leave',
            }
        )

        player.delete()

    return redirect('tournaments:tournaments')


# @api_view(["GET"])
# @permission_classes([IsAuthenticated])
@login_required
def start_tournament(request, tournament_id):
    tournament = get_object_or_404(Tournament, id=tournament_id, created_by=request.user.userprofile)

    if tournament.created_by != request.user.userprofile:
        return redirect('tournaments:waiting_room', tournament_id=tournament.id)

    players = list(TournamentPlayer.objects.filter(tournament=tournament))
    print("Players before shuffle: ", players)
    if len(players) < 4:
        return redirect('tournaments:waiting_room', tournament_id=tournament.id)

    total_rounds = ceil(log2(len(players)))

    with transaction.atomic():
        tournament.status = 'ongoing'
        tournament.save()

        random.shuffle(players)

        num_byes = (2 ** total_rounds) - len(players)
        bye_players = [None] * num_byes
        player_slots = players + bye_players

        print("*********** Player Slots ***********")
        print(player_slots)

        games = []
        create_games(tournament, player_slots, 1, total_rounds, games)

        assign_parent_child_relationships(games)

    group_name = f'tournament_{tournament.id}'
    channel_layer = get_channel_layer()
    async_to_sync(channel_layer.group_send)(
        group_name,
        {
            'type': 'start_tournament',
            'message': 'Tournament started!',
            'redirect_url': reverse('tournaments:tournament_tree', args=[tournament.id]),
        }
    )

    return redirect('tournaments:tournament_tree', tournament_id=tournament.id)


# @api_view(["GET"])
# @permission_classes([IsAuthenticated])
@login_required
def tournament_tree_view(request, tournament_id):
    tournament = get_object_or_404(Tournament, id=tournament_id)
    games = TournamentGame.objects.filter(tournament=tournament).order_by('round_number')
    current_user = request.user.userprofile

    nodes = []
    current_game_url = None
    opponent_name = None
    for game in games:
        print(f"TournamentGame ID: {game.id}, Game Linked: {bool(game.game)}")
        is_current_user_in_game = (
                (game.player_one and game.player_one.player == current_user) or
                (game.player_two and game.player_two.player == current_user)
        )

        if is_current_user_in_game and not current_game_url:
            current_game_url = reverse('game:real_game', kwargs={'game_id': game.game.id}) if game.game else None

        if game.player_one and game.player_one.player == current_user:
            opponent_name = game.player_two.player.display_name if game.player_two else None
        elif game.player_two and game.player_two.player == current_user:
            opponent_name = game.player_one.player.display_name if game.player_one else None

        match_node = {
            "key": f"match-{game.id}",
            "text": f"Match {game.round_number}-{game.id}",
            "round": game.round_number,
            "player_one": game.player_one.player.display_name if game.player_one else None,
            "player_two": game.player_two.player.display_name if game.player_two else None,
            "score_one": game.game.player_one_score if game.game else "0",
            "score_two": game.game.player_two_score if game.game else "0",
            "winner": game.game.winner.display_name if game.game and game.game.winner else None,
            "parent": f"match-{game.parent.id}" if game.parent else None,
            "category": "match",
        }
        nodes.append(match_node)

    links = generate_links(games, tournament)

    return render(request, 'tournaments/tournament_tree.html', {
        'tournament': tournament,
        'nodes': json.dumps(nodes),
        'links': json.dumps(links),
        'current_game_url': current_game_url,
        'opponent_name': opponent_name,
    })


# @api_view(["GET"])
# @permission_classes([IsAuthenticated])
@login_required
def tournament_tree_data(request, tournament_id):
    tournament = get_object_or_404(Tournament, id=tournament_id)
    games = TournamentGame.objects.filter(tournament=tournament).order_by('round_number')
    current_user = request.user.userprofile

    nodes = []
    current_game_url = None
    opponent_name = None

    for game in games:
        print(f"TournamentGame ID: {game.id}, Game Linked: {bool(game.game)}")
        is_current_user_in_game = (
                (game.player_one and game.player_one.player == current_user) or
                (game.player_two and game.player_two.player == current_user)
        )
        if is_current_user_in_game and game.game and not game.game.is_completed:
            current_game_url = reverse('game:real_game', kwargs={'game_id': game.game.id})
        if game.player_one and game.player_one.player == current_user:
            opponent_name = game.player_two.player.display_name if game.player_two else "Bye"
        elif game.player_two and game.player_two.player == current_user:
            opponent_name = game.player_one.player.display_name if game.player_one else "Bye"

        match_node = {
            "key": f"match-{game.id}",
            "text": f"Match {game.round_number}-{game.id}",
            "round": game.round_number,

src/backend/tournaments/templates/tournaments/create_tournament.html
{% extends 'djangoProject/home.html' %}
{% block title %}Create Tournament{% endblock %}
{% block body_attributes %}data-active-page="play"{% endblock %}

{% block content %}
    <div class="create-tournament">
        <h1 class="title"> Create your tournament </h1>
        <form method="post">
            {% csrf_token %}
            <div class="input-form">
                <label for="name">Tournament name</label>
                <input type="text" name="name" id="name" required class="create_tournament_form_input"
                       placeholder="Name">
            </div>
            <button type="submit" class="primary-btn">Create tournament</button>
        </form>
    </div>
{% endblock %}

src/backend/tournaments/templates/tournaments/join_tournament.html
{% extends 'djangoProject/home.html' %}
{% block title %}Join a Tournament{% endblock %}
{% block body_attributes %}data-active-page="play"{% endblock %}

{% block content %}
    <div class="create-tournament">
        <h1 class="title"> Enter the code to join a tournament </h1>
        <form method="post">
            {% csrf_token %}
            <div class="input-form">
                <label for="code">Tournament code :</label>
                <input type="text" name="code" id="code" required placeholder="Code">
            </div>
            <button type="submit" class="primary-btn">Join tournament</button>
        </form>
        {% if error %}
            <p>{{ error }}</p>
        {% endif %}
    </div>
{% endblock %}

src/backend/tournaments/templates/tournaments/tournament_home.html
{% extends 'djangoProject/home.html' %}
{% block title %}Tournaments{% endblock %}
{% block body_attributes %}data-active-page="play"{% endblock %}

{% block content %}
    <div class="tournament">
        <h1 class="tournament_selection_title"> Create or join a Tournament </h1>
        <div class="tournament_buttons">
            <a class="create-tournament-btn tournament-btn" href="{% url 'tournaments:create_tournament' %}">Create a
                tournament</a>
            <a class="join-tournament-btn tournament-btn" href="{% url 'tournaments:join_tournament' %}">Join a
                tournament</a>
        </div>
    </div>
{% endblock %}

src/backend/tournaments/templates/tournaments/tournament_tree.html
{% extends 'djangoProject/home.html' %}
{% block title %}Tournaments Tree{% endblock %}
{% block body_attributes %}data-active-page="play"{% endblock %}
{% load static %}
{% block content %}
    <script src="https://cdn.jsdelivr.net/npm/gojs@3.0/release/go.js"></script>
    <script src="{% static 'js/tournament_tree.js' %}"></script>
    <div class="tournament_tree_container">
        <h1>{{ tournament.name }} - Tournament Tree</h1>

        <div id="tournamentWinner" style="display:none;">
            <h2>Tournament Winner: <span id="winnerName"></span></h2>
        </div>

        <div id="myDiagramDiv"></div>
        <div id="nextGameInfo">
            <p>
                {% if opponent_name %}
                    You will be redirected to your game against {{ opponent_name }} in 5 seconds
                {% else %}
                    You will be redirected to your game in 5 seconds
                {% endif %}
            </p>
        </div>

        <div id="navigationButtons" style="display:none;">
            <a class="btn" href="{% url 'tournaments:tournaments' %}">Back to Tournaments</a>
            <a class="btn" href="{% url 'home' %}">Go Home</a>
        </div>
    </div>
    <script>
        let redirectTimeout;
        let currentGameUrl = "{{ current_game_url }}";
        let opponentName = "{{ opponent_name }}";
        const redirectMessage = document.getElementById("nextGameInfo");

        function checkRedirect(data) {
            if (data.current_game_url) {
                currentGameUrl = data.current_game_url;
                opponentName = data.opponent_name;

                let seconds = 10;
                redirectMessage.style.display = 'block';
                redirectMessage.innerHTML = `You will be redirected to your game against ${opponentName} in ${seconds} seconds`;


                redirectTimeout = setInterval(() => {
                    seconds--;
                    redirectMessage.innerHTML = `You will be redirected to your game against ${opponentName} in ${seconds} seconds`;

                    if (seconds <= 0) {
                        clearInterval(redirectTimeout);
                        window.location.href = currentGameUrl;
                    }
                }, 1000);
            }
            else {
                redirectMessage.style.display = 'none';
                clearInterval(redirectTimeout);
            }
        }

        function refreshTournamentData() {
            fetch("{% url 'tournaments:tournament_tree_data' tournament.id %}")
                .then(response => response.json())
                .then(data => {
                    console.log("Received nodes:", data.nodes);
                    renderTournamentTree(data.nodes, data.links);
                    if (!data.is_completed) {
                        checkRedirect(data);
                    }
                    else {
                        redirectMessage.style.display = 'none';
                        clearInterval(redirectTimeout);
                        document.getElementById("navigationButtons").style.display = 'block';
                        displayTournamentWinner(data.nodes.find(n => n.round === data.nodes.reduce((max, n) => Math.max(max, n.round), 0)).winner);
                    }
                })
                .catch(error => console.error("Error fetching tournament data:", error));
        }

        function displayTournamentWinner(winnerName) {
            document.getElementById("winnerName").innerText = winnerName;
            document.getElementById("tournamentWinner").style.display = 'block';
        }

        const wsProtocol = window.location.protocol === 'https:' ? 'wss://' : 'ws://';
        const wsPath = `${wsProtocol}${window.location.host}/ws/tournaments/{{ tournament.id }}/`;
        const socket = new WebSocket(wsPath);

        socket.onmessage = function (e) {
            const data = JSON.parse(e.data);
            if (data.type === 'tournament_update' && data.action === 'game_completed') {
                console.log("Game completed, refreshing tournament tree...");
                refreshTournamentData();
                window.location.reload();
            }
        };

        // Initial setup
        refreshTournamentData();
        if (currentGameUrl) {
            checkRedirect({
                current_game_url: currentGameUrl,
                opponent_name: opponentName
            });
        }
    </script>

{% endblock %}

src/backend/tournaments/templates/tournaments/tournament_waiting_room.html
{% extends 'djangoProject/home.html' %}
{% block title %}Tournament details{% endblock %}
{% load static %}
{% block body_attributes %}data-active-page="play"{% endblock %}
{% block content %}
    <h2 class="tournament_waitingRoom_title"> {{ tournament.name }} </h2>
    <div class="tournament_waiting_room_container">
        <div class="code_to_join_container">
            <p class="join_code">Code to join the game : <strong>{{ tournament.tournament_code_join }}</strong></p>
        </div>
        <div class="creator_tournament_container">
            <p>Tournament created by : <strong>{{ tournament.created_by.user.username }}</strong></p>
        </div>
        <div class="tournament_status_container">
            <p>Status :<strong>{{ tournament.status }}</strong></p>
        </div>
        <div class="tournament_player_list_container">
            <h2>Players in the game : <span id="connected-count">0</span></h2>
            <ul id="players_list">
                {% for player in players %}
                    <li>{{ player.user.username }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="tournament_waiting_room_buttons">
            {% if current_user == tournament.created_by.user %}
                <a class="primary-btn" id="start-button" href="{% url "tournaments:start_tournament" tournament.id %}"
                   style="display:none;">Start the tournament</a>
                <button class="btn" onclick="confirmCancel()">Cancel</button>
            {% endif %}
            {% if current_user != tournament.created_by.user %}
                <button class="btn" onclick="confirmLeave()">Leave Tournament</button>
            {% endif %}
        </div>
    </div>
    <script> const tournamentID = "{{ tournament.id }}"</script>
    <script>
        function confirmCancel() {
            if (confirm("Are you sure you want to cancel this tournament?")) {
                window.location.href = '{% url "tournaments:cancel_tournament" tournament.id %}';
            }
        }

        function confirmLeave() {
            if (confirm("Are you sure you want to leave this tournament?")) {
                window.location.href = '{% url "tournaments:leave_tournament" tournament.id %}';
            }
        }
    </script>
    <script src="{% static 'js/waiting_room.js' %}"></script>

{% endblock %}
